import "server-only";
import { supabaseAdmin } from "@/lib/supabase/admin";
import {
  costOfActionExact,
  ACTIVE_MODEL,
  type AiFeature,
  type TokenUsage,
} from "./cost-model";
import { getImageCost } from "./image-cost";

/*
 * AI usage ledger writer — records the REAL cost of one AI action.
 *
 * Called from the API layer right after an action succeeds and credits are
 * charged. Best-effort by design: a logging failure must NEVER break the user's
 * action or the credit charge, so every path is caught and swallowed (the credit
 * ledger remains the source of truth for billing; this is the cost/analytics
 * layer on top). Cost is computed here from real measured usage via the cost
 * model, so the number stored is exact, not estimated.
 */

export interface RecordAiUsageInput {
  userId: string;
  feature: AiFeature;
  /** Credits the user was charged (mirror of the credit_ledger delta). */
  credits: number;
  /** Real token usage off the provider response. Omit for pure-image actions. */
  usage?: TokenUsage;
  /** Images generated by this action. */
  images?: number;
  /** The model used (any string — models are env-routable). Stored verbatim;
   *  unpriced models fall back to the default's rate for the cost estimate. */
  model?: string;
  requestId?: string;
}

export async function recordAiUsage(input: RecordAiUsageInput): Promise<void> {
  try {
    const usage: TokenUsage = input.usage ?? { inputTokens: 0, outputTokens: 0 };
    const images = input.images ?? 0;
    const model = input.model ?? ACTIVE_MODEL;
    /*
     * Resolve the per-image rate in force rather than using the code default,
     * so a corrected Higgsfield price applies from the next action onward with
     * no deploy. Only read when the action actually produced images — no reason
     * to pay a settings round-trip on a text-only call.
     */
    const imageRate = images > 0 ? (await getImageCost()).rateUsd : undefined;
    const cost = costOfActionExact(usage, images, model, imageRate);

    await supabaseAdmin()
      .from("ai_usage_ledger")
      .insert({
        user_id: input.userId,
        feature: input.feature,
        credits: input.credits,
        input_tokens: usage.inputTokens,
        output_tokens: usage.outputTokens,
        images,
        model,
        anthropic_cost_usd: round6(cost.anthropicUsd),
        image_cost_usd: round6(cost.imageUsd),
        total_cost_usd: round6(cost.totalUsd),
        request_id: input.requestId ?? null,
      });
  } catch {
    // Intentionally swallowed — cost logging is never allowed to affect the
    // user action or the billing charge. (Sentry hook can be added here later.)
  }
}

function round6(n: number): number {
  return Math.round(n * 1e6) / 1e6;
}
