import Image from "next/image";
import logo from "@/assets/brand/urivo-logo.png";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center px-6 py-24 text-center">
      <Image
        src={logo}
        alt="Urivo"
        width={112}
        height={112}
        priority
        className="rounded-[28px] shadow-2xl shadow-forest-950/60"
      />

      <p className="mt-12 text-[11px] font-semibold uppercase tracking-[0.25em] text-gold-500">
        The AI Commerce Operating System
      </p>

      <h1 className="mt-6 max-w-3xl font-serif text-5xl font-normal leading-tight tracking-tight text-ivory-100 sm:text-6xl">
        Describe your business.
        <br />
        Urivo builds it.
      </h1>

      <p className="mt-8 max-w-xl text-lg font-light leading-relaxed text-ivory-100/70">
        Market research, brand identity, product catalog and a live storefront —
        generated by AI, refined by you.
      </p>

      <p className="mt-16 border-t border-ivory-100/10 pt-8 text-[11px] font-semibold uppercase tracking-[0.25em] text-ivory-100/40">
        Founder pricing opens 23 July
      </p>
    </main>
  );
}
