import Link from "next/link";
import Image from "next/image";
import logo from "@/assets/brand/urivo-logo.png";

/*
 * Marketing landing page — Design System v2 (light, Slate/Gold, Linear feel).
 * Self-contained light theme; launch pricing driven by the server clock.
 */

const LAUNCH_START = new Date("2026-07-23T00:00:00Z");
const LAUNCH_END = new Date("2026-08-15T23:59:59Z");
function isLaunchWindow(now = new Date()): boolean {
  return now >= LAUNCH_START && now <= LAUNCH_END;
}

const TIERS = [
  {
    name: "Free",
    launch: "€0",
    standard: "€0",
    cadence: "forever",
    features: ["15 credits, one-time", "1 live storefront", "5 products", "urivo.ai subdomain"],
    cta: "Start free",
    highlight: false,
  },
  {
    name: "Core",
    launch: "€49",
    standard: "€79",
    cadence: "/ month",
    features: ["Monthly credit allowance", "Multiple storefronts", "Unlimited products", "Analytics dashboard"],
    cta: "Choose Core",
    highlight: true,
  },
  {
    name: "Pro",
    launch: "€199",
    standard: "€299",
    cadence: "/ month",
    features: ["Higher credit allowance", "Custom domains", "Priority generation", "Everything in Core"],
    cta: "Choose Pro",
    highlight: false,
  },
];

export default function Home() {
  const launch = isLaunchWindow();

  return (
    <div className="min-h-screen bg-canvas text-ink">
      {/* Nav */}
      <header className="sticky top-0 z-40 border-b border-line bg-canvas/80 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2.5">
            <Image src={logo} alt="Urivo" width={32} height={32} className="rounded-md" />
            <span className="text-lg font-semibold tracking-tight text-brand">Urivo</span>
          </div>
          <div className="flex items-center gap-6 text-sm font-medium">
            <Link href="#pricing" className="text-muted transition-colors hover:text-ink">
              Pricing
            </Link>
            <Link
              href="/login"
              className="rounded-md bg-brand px-4 py-2 text-sm font-semibold text-white shadow-soft transition-all duration-200 ease-(--ease-urivo) hover:-translate-y-0.5 hover:bg-brand-hover"
            >
              Sign in
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="mx-auto max-w-4xl px-6 py-24 text-center sm:py-32">
        <div className="mx-auto mb-8 inline-flex items-center gap-2 rounded-full border border-line bg-surface px-4 py-1.5 text-xs font-semibold text-muted shadow-soft">
          <span className="h-1.5 w-1.5 rounded-full bg-gold" />
          The AI Commerce Operating System
        </div>
        <h1 className="text-5xl font-semibold leading-[1.05] tracking-tight text-ink sm:text-7xl">
          Describe your business.
          <br />
          <span className="text-brand">Urivo builds it.</span>
        </h1>
        <p className="mx-auto mt-8 max-w-xl text-lg leading-relaxed text-muted">
          Market research, brand identity, product catalog and a live storefront —
          generated by AI in under a minute, refined by you.
        </p>
        <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
          <Link
            href="/login"
            className="w-full rounded-md bg-brand px-8 py-3.5 text-sm font-semibold text-white shadow-soft transition-all duration-200 ease-(--ease-urivo) hover:-translate-y-0.5 hover:bg-brand-hover sm:w-auto"
          >
            Start free
          </Link>
          <Link
            href="#pricing"
            className="w-full rounded-md border border-line bg-surface px-8 py-3.5 text-sm font-semibold text-ink transition-colors hover:bg-surface-muted sm:w-auto"
          >
            See pricing
          </Link>
        </div>
      </section>

      {/* How it works */}
      <section className="mx-auto max-w-5xl px-6 py-16">
        <div className="grid gap-6 sm:grid-cols-3">
          {[
            ["Describe", "Tell Urivo what you want to sell — one sentence is enough."],
            ["Generate", "AI designs your brand, writes your catalog and builds the store."],
            ["Sell", "Your storefront goes live on its own address, ready to refine."],
          ].map(([title, body], i) => (
            <div key={title} className="rounded-lg border border-line bg-surface p-8 shadow-soft">
              <div className="flex h-9 w-9 items-center justify-center rounded-md bg-brand-soft text-sm font-semibold text-brand">
                {i + 1}
              </div>
              <h3 className="mt-5 text-lg font-semibold text-ink">{title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-muted">{body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="mx-auto max-w-6xl px-6 py-24">
        <div className="text-center">
          {launch && (
            <span className="mb-5 inline-block rounded-full bg-gold-tint px-4 py-1.5 text-xs font-semibold tracking-wide text-[#8a6d18]">
              Founder pricing — locked for life, until 15 August
            </span>
          )}
          <h2 className="text-4xl font-semibold tracking-tight text-ink">Simple, premium pricing</h2>
        </div>

        <div className="mt-14 grid gap-6 md:grid-cols-3">
          {TIERS.map((tier) => (
            <div
              key={tier.name}
              className={`flex flex-col rounded-lg border bg-surface p-8 shadow-soft ${
                tier.highlight ? "border-brand ring-1 ring-brand/10" : "border-line"
              }`}
            >
              {tier.highlight && (
                <span className="mb-4 self-start rounded-full bg-brand px-3 py-1 text-xs font-semibold text-white">
                  Most popular
                </span>
              )}
              <h3 className="text-xl font-semibold text-ink">{tier.name}</h3>
              <div className="mt-5 flex items-baseline gap-2">
                <span className="text-5xl font-semibold tracking-tight text-ink">
                  {launch ? tier.launch : tier.standard}
                </span>
                {launch && tier.launch !== tier.standard && (
                  <span className="text-lg text-muted line-through">{tier.standard}</span>
                )}
              </div>
              <p className="mt-1 text-sm text-muted">{tier.cadence}</p>

              <ul className="mt-8 flex-1 space-y-3 text-sm text-ink/80">
                {tier.features.map((f) => (
                  <li key={f} className="flex items-start gap-2.5">
                    <svg className="mt-0.5 h-4 w-4 shrink-0 text-gold" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.7 5.3a1 1 0 0 1 0 1.4l-7.5 7.5a1 1 0 0 1-1.4 0L3.3 9.7a1 1 0 1 1 1.4-1.4l3.3 3.3 6.8-6.8a1 1 0 0 1 1.4 0Z" clipRule="evenodd" />
                    </svg>
                    {f}
                  </li>
                ))}
              </ul>

              <Link
                href="/login"
                className={`mt-8 rounded-md px-6 py-3 text-center text-sm font-semibold transition-all duration-200 ease-(--ease-urivo) hover:-translate-y-0.5 ${
                  tier.highlight
                    ? "bg-brand text-white shadow-soft hover:bg-brand-hover"
                    : "border border-line bg-surface text-ink hover:bg-surface-muted"
                }`}
              >
                {tier.cta}
              </Link>
            </div>
          ))}
        </div>
        <p className="mt-8 text-center text-sm text-muted">
          {launch
            ? "Subscribe during the launch window and keep your price for the lifetime of your subscription."
            : "Prices in EUR. Cancel anytime."}
        </p>
      </section>

      {/* Footer */}
      <footer className="border-t border-line bg-surface">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 px-6 py-10 sm:flex-row">
          <p className="text-sm text-muted">© {new Date().getFullYear()} Urivo</p>
          <div className="flex gap-6 text-sm font-medium text-muted">
            <Link href="/impressum" className="hover:text-ink">Impressum</Link>
            <Link href="/datenschutz" className="hover:text-ink">Datenschutz</Link>
            <Link href="/agb" className="hover:text-ink">AGB</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
