import Link from "next/link";
import Image from "next/image";
import logo from "@/assets/brand/urivo-logo.png";

/*
 * Marketing landing page (screens-v1 §1, spec 6.8 pricing display).
 * Launch pricing is shown during the window (23 Jul – 15 Aug 2026);
 * the countdown/launch badge is driven by the server clock, not a client flag.
 */

const LAUNCH_START = new Date("2026-07-23T00:00:00Z");
const LAUNCH_END = new Date("2026-08-15T23:59:59Z");

function isLaunchWindow(now = new Date()): boolean {
  return now >= LAUNCH_START && now <= LAUNCH_END;
}

const TIERS = [
  {
    name: "Free",
    launch: "€0",
    standard: "€0",
    cadence: "forever",
    features: ["15 credits, one-time", "1 live storefront", "5 products", "urivo.ai subdomain"],
    cta: "Start free",
    highlight: false,
  },
  {
    name: "Core",
    launch: "€49",
    standard: "€79",
    cadence: "/ month",
    features: [
      "Monthly credit allowance",
      "Multiple storefronts",
      "Unlimited products",
      "Analytics dashboard",
    ],
    cta: "Choose Core",
    highlight: true,
  },
  {
    name: "Pro",
    launch: "€199",
    standard: "€299",
    cadence: "/ month",
    features: [
      "Higher credit allowance",
      "Custom domains",
      "Priority generation",
      "Everything in Core",
    ],
    cta: "Choose Pro",
    highlight: false,
  },
];

export default function Home() {
  const launch = isLaunchWindow();

  return (
    <div className="min-h-screen">
      {/* Nav */}
      <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6">
        <div className="flex items-center gap-3">
          <Image src={logo} alt="Urivo" width={36} height={36} className="rounded-lg" />
          <span className="font-serif text-lg tracking-wide text-ivory-100">Urivo</span>
        </div>
        <div className="flex items-center gap-6 text-[11px] font-semibold uppercase tracking-[0.2em]">
          <Link href="#pricing" className="text-ivory-100/60 hover:text-ivory-100">
            Pricing
          </Link>
          <Link href="/login" className="text-gold-300 hover:text-champagne">
            Sign in
          </Link>
        </div>
      </header>

      {/* Hero */}
      <section className="mx-auto max-w-4xl px-6 py-24 text-center sm:py-32">
        <p className="text-[11px] font-semibold uppercase tracking-[0.25em] text-gold-500">
          The AI Commerce Operating System
        </p>
        <h1 className="mt-6 font-serif text-5xl font-normal leading-tight tracking-tight text-ivory-100 sm:text-7xl">
          Describe your business.
          <br />
          Urivo builds it.
        </h1>
        <p className="mx-auto mt-8 max-w-xl text-lg font-light leading-relaxed text-ivory-100/70">
          Market research, brand identity, product catalog and a live storefront —
          generated by AI in under a minute, refined by you.
        </p>
        <div className="mt-12 flex flex-col items-center justify-center gap-4 sm:flex-row">
          <Link
            href="/login"
            className="rounded-lg bg-gold-500 px-8 py-4 text-[11px] font-semibold uppercase tracking-[0.25em] text-forest-900 transition-all duration-200 ease-(--ease-urivo) hover:-translate-y-0.5 hover:bg-champagne"
          >
            Start free
          </Link>
          <Link
            href="#pricing"
            className="rounded-lg border border-ivory-100/15 px-8 py-4 text-[11px] font-semibold uppercase tracking-[0.25em] text-ivory-100/70 transition-colors hover:border-ivory-100/30 hover:text-ivory-100"
          >
            See pricing
          </Link>
        </div>
      </section>

      {/* How it works */}
      <section className="mx-auto max-w-5xl px-6 py-20">
        <div className="grid gap-10 sm:grid-cols-3">
          {[
            ["01", "Describe", "Tell Urivo what you want to sell — one sentence is enough."],
            ["02", "Generate", "AI designs your brand, writes your catalog and builds the store."],
            ["03", "Sell", "Your storefront goes live on its own address, ready to refine."],
          ].map(([n, title, body]) => (
            <div key={n}>
              <p className="font-serif text-3xl text-gold-500">{n}</p>
              <h3 className="mt-4 text-[11px] font-semibold uppercase tracking-[0.25em] text-ivory-100">
                {title}
              </h3>
              <p className="mt-3 text-sm font-light leading-relaxed text-ivory-100/60">{body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="mx-auto max-w-6xl px-6 py-24">
        <div className="text-center">
          {launch && (
            <span className="mb-6 inline-block rounded-full border border-gold-500/30 bg-gold-500/10 px-4 py-1.5 text-[10px] font-semibold uppercase tracking-[0.25em] text-gold-300">
              Founder pricing — locked for life, until 15 August
            </span>
          )}
          <h2 className="font-serif text-4xl font-normal tracking-tight text-ivory-100">
            Simple, premium pricing
          </h2>
        </div>

        <div className="mt-16 grid gap-6 md:grid-cols-3">
          {TIERS.map((tier) => (
            <div
              key={tier.name}
              className={`flex flex-col rounded-2xl border p-8 ${
                tier.highlight
                  ? "border-gold-500/40 bg-ivory-100/5"
                  : "border-ivory-100/10 bg-ivory-100/[0.03]"
              }`}
            >
              {tier.highlight && (
                <span className="mb-4 self-start rounded-full bg-gold-500 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-forest-900">
                  Most popular
                </span>
              )}
              <h3 className="font-serif text-2xl font-normal text-ivory-100">{tier.name}</h3>
              <div className="mt-6 flex items-baseline gap-2">
                <span className="font-serif text-5xl font-light text-ivory-100">
                  {launch ? tier.launch : tier.standard}
                </span>
                {launch && tier.launch !== tier.standard && (
                  <span className="text-lg font-light text-ivory-100/40 line-through">
                    {tier.standard}
                  </span>
                )}
              </div>
              <p className="mt-1 text-sm font-light text-ivory-100/50">{tier.cadence}</p>

              <ul className="mt-8 flex-1 space-y-3 text-sm font-light text-ivory-100/70">
                {tier.features.map((f) => (
                  <li key={f} className="flex items-start gap-2">
                    <span className="text-gold-500">✦</span>
                    {f}
                  </li>
                ))}
              </ul>

              <Link
                href="/login"
                className={`mt-8 rounded-lg px-6 py-3.5 text-center text-[11px] font-semibold uppercase tracking-[0.25em] transition-all duration-200 ease-(--ease-urivo) hover:-translate-y-0.5 ${
                  tier.highlight
                    ? "bg-gold-500 text-forest-900 hover:bg-champagne"
                    : "border border-ivory-100/15 text-ivory-100/80 hover:border-ivory-100/30 hover:text-ivory-100"
                }`}
              >
                {tier.cta}
              </Link>
            </div>
          ))}
        </div>
        <p className="mt-8 text-center text-xs font-light text-ivory-100/40">
          {launch
            ? "Subscribe during the launch window and keep your price for the lifetime of your subscription."
            : "Prices in EUR. Cancel anytime."}
        </p>
      </section>

      {/* Footer */}
      <footer className="border-t border-ivory-100/10">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 px-6 py-10 sm:flex-row">
          <p className="text-xs font-light text-ivory-100/40">
            © {new Date().getFullYear()} Urivo
          </p>
          <div className="flex gap-6 text-[11px] font-semibold uppercase tracking-[0.2em] text-ivory-100/50">
            <Link href="/impressum" className="hover:text-ivory-100">
              Impressum
            </Link>
            <Link href="/datenschutz" className="hover:text-ivory-100">
              Datenschutz
            </Link>
            <Link href="/agb" className="hover:text-ivory-100">
              AGB
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
