import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

/*
 * setup_all.sql drift.
 *
 * supabase/setup_all.sql is the launch provisioning path: a fresh Supabase
 * project is created by pasting that one file. It is generated by
 * `npm run db:build`, and generation is a manual step someone has to remember
 * after adding a migration.
 *
 * Nobody remembered once. The build script's own header records it: the file
 * sat twelve migrations behind the folder, which would have produced a subtly
 * broken database on launch day. The failure is completely silent — the paste
 * succeeds, every screen renders, and the only symptom is whatever the missing
 * migrations were protecting. Migration 0045 is the sharpest example: a
 * database provisioned without it has no symptoms at all, and the paid tiers
 * are simply free.
 *
 * So the reminder is a test instead of a habit.
 */

const ROOT = join(__dirname, "..");
const MIGRATIONS = join(ROOT, "supabase", "migrations");

describe("setup_all.sql carries every migration", () => {
  const migrations = readdirSync(MIGRATIONS)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  const setup = readFileSync(join(ROOT, "supabase", "setup_all.sql"), "utf8");

  it("names every migration file in order", () => {
    // The generator writes each file's name as a section header, so a missing
    // migration is a missing header — and the order is the order it applies in.
    const missing = migrations.filter((f) => !setup.includes(f));
    expect(
      missing,
      `setup_all.sql is stale. Run: npm run db:build\nMissing:\n${missing.join("\n")}`,
    ).toEqual([]);
  });

  it("lists them in the same order as the folder", () => {
    const positions = migrations.map((f) => setup.indexOf(f));
    const sorted = [...positions].sort((a, b) => a - b);
    expect(positions, "setup_all.sql applies migrations out of order").toEqual(sorted);
  });

  it("advertises the real range in its header", () => {
    // The header tells whoever pastes it what they are getting. A stale range
    // is the one part of a stale file a human might actually notice.
    const first = migrations[0].slice(0, 4);
    const last = migrations[migrations.length - 1].slice(0, 4);
    expect(setup).toContain(`migrations ${first}–${last}`);
  });
});
