import Link from "next/link";
import Image from "next/image";
import logo from "@/assets/brand/urivo-logo.png";

/*
 * Marketing landing — Midnight (dark slate-navy, warm ivory, metallic gold).
 * Self-contained dark theme; launch pricing driven by the server clock.
 */

const LAUNCH_START = new Date("2026-07-23T00:00:00Z");
const LAUNCH_END = new Date("2026-08-15T23:59:59Z");
function isLaunchWindow(now = new Date()): boolean {
  return now >= LAUNCH_START && now <= LAUNCH_END;
}

const TIERS = [
  {
    name: "Free",
    launch: "€0",
    standard: "€0",
    cadence: "forever",
    features: ["15 credits, one-time", "1 live storefront", "5 products", "urivo.ai subdomain"],
    cta: "Start free",
    highlight: false,
  },
  {
    name: "Core",
    launch: "€49",
    standard: "€79",
    cadence: "/ month",
    features: ["Monthly credit allowance", "Multiple storefronts", "Unlimited products", "Analytics dashboard"],
    cta: "Choose Core",
    highlight: true,
  },
  {
    name: "Pro",
    launch: "€199",
    standard: "€299",
    cadence: "/ month",
    features: ["Higher credit allowance", "Custom domains", "Priority generation", "Everything in Core"],
    cta: "Choose Pro",
    highlight: false,
  },
];

export default function Home() {
  const launch = isLaunchWindow();

  return (
    <div className="relative min-h-screen overflow-hidden bg-night text-ivory">
      {/* ambient */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(60% 40% at 50% -5%, rgba(232,205,128,0.10), rgba(11,18,32,0) 55%), radial-gradient(70% 50% at 50% 8%, rgba(36,50,76,0.5), rgba(11,18,32,0) 60%)",
        }}
      />

      {/* Nav */}
      <header className="u-glass sticky top-0 z-40 border-b border-hair">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2.5">
            <Image src={logo} alt="Urivo" width={30} height={30} className="rounded-lg" />
            <span className="text-lg font-semibold tracking-tight text-ivory">Urivo</span>
          </div>
          <div className="flex items-center gap-6 text-sm font-medium">
            <Link href="#pricing" className="hidden text-mist transition-colors hover:text-ivory sm:block">
              Pricing
            </Link>
            <Link href="#faq" className="hidden text-mist transition-colors hover:text-ivory sm:block">
              FAQ
            </Link>
            <Link href="/login" className="u-lift rounded-lg border border-hair bg-panel px-4 py-2 text-sm font-medium text-ivory hover:border-hair-strong hover:bg-panel-2">
              Sign in
            </Link>
            <Link href="/login" className="u-gold u-lift rounded-lg px-4 py-2 text-sm font-semibold">
              Get started
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative mx-auto max-w-4xl px-6 pt-24 text-center sm:pt-28">
        <div className="u-glass mx-auto mb-8 inline-flex items-center gap-2 rounded-full border border-hair px-4 py-1.5 text-xs font-semibold text-gold-soft">
          <span className="h-1.5 w-1.5 rounded-full bg-gold" style={{ boxShadow: "0 0 8px rgba(232,205,128,0.7)" }} />
          The AI Commerce Operating System
        </div>
        <h1 className="text-5xl font-semibold leading-[1.05] tracking-tight text-ivory sm:text-7xl">
          Describe your business.
          <br />
          <span className="u-gold-text">Urivo builds it.</span>
        </h1>
        <p className="mx-auto mt-8 max-w-xl text-lg leading-relaxed text-mist">
          Market research, brand identity, product catalog and a live storefront —
          generated by AI in under a minute, refined by you.
        </p>
        <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
          <Link href="/login" className="u-gold u-lift w-full rounded-xl px-8 py-3.5 text-sm font-semibold sm:w-auto">
            Start your store →
          </Link>
          <Link href="#pricing" className="u-lift w-full rounded-xl border border-hair bg-panel px-8 py-3.5 text-sm font-semibold text-ivory hover:border-hair-strong hover:bg-panel-2 sm:w-auto">
            See pricing
          </Link>
        </div>
        <p className="mt-5 text-xs text-mist-dim">No credit card required</p>
      </section>

      {/* Product visual */}
      <section className="relative mx-auto mt-16 max-w-5xl px-6">
        <div className="u-float overflow-hidden rounded-2xl border border-hair bg-panel/70">
          <div className="flex items-center gap-1.5 border-b border-hair px-4 py-2.5">
            <span className="h-2.5 w-2.5 rounded-full bg-alert/70" />
            <span className="h-2.5 w-2.5 rounded-full bg-gold/70" />
            <span className="h-2.5 w-2.5 rounded-full bg-live/70" />
            <span className="mx-auto rounded-md bg-night px-3 py-1 font-mono text-[11px] text-mist-dim">nordljus.urivo.ai</span>
          </div>
          <div className="grid gap-0 sm:grid-cols-[1fr_1.3fr]">
            <div className="border-b border-hair p-8 sm:border-b-0 sm:border-r" style={{ background: "#F2EFE9", color: "#242A33" }}>
              <p className="text-[10px] font-semibold uppercase tracking-[0.2em] opacity-50">New collection</p>
              <h3 className="mt-3 text-4xl font-semibold leading-none tracking-tight" style={{ fontFamily: "Georgia, serif" }}>
                Nordljus
              </h3>
              <p className="mt-2 text-sm italic opacity-70">Quiet luxury for the Scandinavian home.</p>
              <span className="mt-6 inline-block rounded-md px-4 py-2 text-xs font-semibold" style={{ background: "#242A33", color: "#F2EFE9" }}>
                Shop collection
              </span>
            </div>
            <div className="grid grid-cols-2 gap-4 p-8" style={{ background: "#F6F4EF" }}>
              {["€42", "€128", "€76", "€154"].map((p, i) => (
                <div key={i} className="rounded-lg p-3" style={{ background: "#fff" }}>
                  <div className="aspect-square rounded" style={{ background: "#EDE9E1" }} />
                  <div className="mt-2 flex items-center justify-between">
                    <span className="h-1.5 w-10 rounded-full" style={{ background: "#D8D2C6" }} />
                    <span className="text-xs font-semibold" style={{ color: "#B0842F" }}>{p}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="mx-auto max-w-5xl px-6 py-24">
        <div className="grid gap-4 sm:grid-cols-3">
          {[
            ["Describe", "Tell Urivo what you want to sell — one sentence is enough."],
            ["Generate", "AI designs your brand, writes your catalog and builds the store."],
            ["Sell", "Your storefront goes live on its own address, ready to refine."],
          ].map(([title, body], i) => (
            <div key={title} className="u-float rounded-2xl border border-hair bg-panel/70 p-7">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg border border-gold/20 bg-gold/[0.06] text-sm font-semibold text-gold">
                {i + 1}
              </div>
              <h3 className="mt-5 text-lg font-semibold text-ivory">{title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-mist">{body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="mx-auto max-w-6xl px-6 pb-24">
        <div className="text-center">
          {launch && (
            <span className="mb-5 inline-block rounded-full border border-gold/25 bg-gold/[0.06] px-4 py-1.5 text-xs font-semibold tracking-wide text-gold-soft">
              Founder pricing — locked for life, until 15 August
            </span>
          )}
          <h2 className="text-4xl font-semibold tracking-tight text-ivory">Simple, premium pricing</h2>
        </div>

        <div className="mt-14 grid gap-6 md:grid-cols-3">
          {TIERS.map((tier) => (
            <div
              key={tier.name}
              className={`u-float flex flex-col rounded-2xl border bg-panel/70 p-8 ${
                tier.highlight ? "border-gold/40 ring-1 ring-gold/15" : "border-hair"
              }`}
            >
              {tier.highlight && (
                <span className="u-gold mb-4 self-start rounded-full px-3 py-1 text-xs font-semibold">Most popular</span>
              )}
              <h3 className="text-xl font-semibold text-ivory">{tier.name}</h3>
              <div className="mt-5 flex items-baseline gap-2">
                <span className="text-5xl font-semibold tracking-tight text-ivory">
                  {launch ? tier.launch : tier.standard}
                </span>
                {launch && tier.launch !== tier.standard && (
                  <span className="text-lg text-mist line-through">{tier.standard}</span>
                )}
              </div>
              <p className="mt-1 text-sm text-mist">{tier.cadence}</p>

              <ul className="mt-8 flex-1 space-y-3 text-sm text-ivory/85">
                {tier.features.map((f) => (
                  <li key={f} className="flex items-start gap-2.5">
                    <svg className="mt-0.5 h-4 w-4 shrink-0 text-gold" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.7 5.3a1 1 0 0 1 0 1.4l-7.5 7.5a1 1 0 0 1-1.4 0L3.3 9.7a1 1 0 1 1 1.4-1.4l3.3 3.3 6.8-6.8a1 1 0 0 1 1.4 0Z" clipRule="evenodd" />
                    </svg>
                    {f}
                  </li>
                ))}
              </ul>

              <Link
                href="/login"
                className={`u-lift mt-8 rounded-xl px-6 py-3 text-center text-sm font-semibold ${
                  tier.highlight ? "u-gold" : "border border-hair bg-panel text-ivory hover:border-hair-strong hover:bg-panel-2"
                }`}
              >
                {tier.cta}
              </Link>
            </div>
          ))}
        </div>
        <p className="mt-8 text-center text-sm text-mist">
          {launch
            ? "Subscribe during the launch window and keep your price for the lifetime of your subscription."
            : "Prices in EUR. Cancel anytime."}
        </p>
      </section>

      {/* FAQ */}
      <section id="faq" className="mx-auto max-w-3xl px-6 pb-24">
        <h2 className="text-center text-3xl font-semibold tracking-tight text-ivory">Questions, answered</h2>
        <div className="u-float mt-10 divide-y divide-hair overflow-hidden rounded-2xl border border-hair bg-panel/70">
          {[
            ["What exactly does Urivo build for me?", "A complete storefront: a brand name and identity, a curated product catalog with copy and pricing, and a live store on its own web address — generated by AI from a single sentence, then fully editable by you."],
            ["How do credits work?", "Every account starts with 15 free credits. Generating a store costs 10 credits. Paid plans include a recurring monthly credit allowance, and your credit history is always visible in Billing."],
            ["Do I need my own domain?", "No. Every store goes live instantly on a free urivo.ai address. On the Pro plan you can connect your own custom domain whenever you're ready."],
            ["Is the founder pricing really locked for life?", "Yes. Subscribe during the launch window and your price stays fixed for the lifetime of your subscription — even as standard prices rise."],
            ["Can I cancel anytime?", "Anytime, in one click from Billing. You keep access until the end of your current billing period, and you can resubscribe whenever you like."],
          ].map(([q, a]) => (
            <details key={q} className="group px-6 py-5 [&_summary::-webkit-details-marker]:hidden">
              <summary className="flex cursor-pointer items-center justify-between gap-4 text-base font-medium text-ivory">
                {q}
                <svg className="h-5 w-5 shrink-0 text-gold transition-transform duration-200 group-open:rotate-45" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round">
                  <path d="M10 4v12M4 10h12" />
                </svg>
              </summary>
              <p className="mt-3 text-sm leading-relaxed text-mist">{a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-hair">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 px-6 py-10 sm:flex-row">
          <div className="flex items-center gap-2.5">
            <Image src={logo} alt="Urivo" width={22} height={22} className="rounded-md" />
            <p className="text-sm text-mist">© {new Date().getFullYear()} Urivo</p>
          </div>
          <div className="flex gap-6 text-sm font-medium text-mist">
            <Link href="/impressum" className="hover:text-ivory">Impressum</Link>
            <Link href="/datenschutz" className="hover:text-ivory">Datenschutz</Link>
            <Link href="/agb" className="hover:text-ivory">AGB</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
