import Link from "next/link";
import Image from "next/image";
import logo from "@/assets/brand/urivo-logo.png";
import { PLANS, formatPrice } from "@/lib/plans";
import { getFoundingOffer } from "@/lib/platform/settings";
import { CREDIT_COSTS } from "@/lib/credit-costs";
import { Reveal } from "./_motion/reveal";
import { RevealStagger } from "./_motion/reveal-stagger";

/*
 * Marketing landing — Midnight (dark slate-navy, warm ivory, metallic gold).
 * Self-contained dark theme; Founding 50 pricing driven by the live counter.
 * Tiers are read from the plans source of truth so the deck, the landing page
 * and the product never drift.
 */

/*
 * Rendered per request, because the price on it is live state.
 *
 * This page reads the Founding 50 counter, and a spot is claimed by any signup
 * at any moment. Prerendered at build time it would serve whatever the counter
 * said at deploy — so the 51st visitor would still be quoted €29 until someone
 * happened to redeploy. A marketing page may be stale about its wording; it may
 * not be stale about its price.
 *
 * It also decouples the build from the database: a static export had to reach
 * Supabase with a service-role key to render the landing page, which is a
 * secret CI has no business holding.
 *
 * The cost is one primary-key read per visit. If that ever shows up in TTFB,
 * the answer is a short revalidate window here — not baking the price in.
 */
export const dynamic = "force-dynamic";

/*
 * Pricing cards, driven by the same PLANS object billing charges from.
 *
 * `founding` is the real Founding 50 price (migration 0023): a spot is claimed
 * atomically at SIGNUP, stamped on profiles.price_type, and read back by
 * /api/checkout to set the Stripe unit_amount. So the discounted number here is
 * the number the card is charged — not a marketing figure that happens to sit
 * near one.
 *
 * Note this is NOT price.launch. launch and regular are both €49 / €199 today,
 * so a card driven off that pair renders no discount at all and quietly showed
 * standard pricing under a founder-pricing banner.
 */
const TIERS = [PLANS.free, PLANS.core, PLANS.pro].map((p) => ({
  name: p.name,
  founding: typeof p.price.founding === "number" ? formatPrice(p.price.founding) : null,
  standard: formatPrice(p.price.regular),
  cadence: p.key === "free" ? "forever" : "/ month",
  features: p.highlights,
  cta: p.key === "free" ? "Start free" : `Choose ${p.name}`,
  highlight: p.key === "core",
}));

/*
 * The FAQ is a promise, so it is built from the same constants as the product
 * rather than typed out beside them. It was typed out beside them, and drifted:
 * it advertised 20 welcome credits against a pricing table promising 25, quoted
 * 1 credit for an assistant message that costs 2, and told free users they had
 * to upgrade to publish — months after Free was given a live store on purpose.
 * A visitor comparing the pricing card to the answer below it found Urivo
 * contradicting itself on a single screen.
 */
const FAQ = (foundingOpen: boolean): [string, string][] => [
  [
    "What exactly does Urivo build for me?",
    "A complete storefront: a brand name and identity, a curated product catalog with copy and pricing, and a live store on its own web address — generated by AI from a single sentence, then fully editable by you.",
  ],
  [
    "How do credits work?",
    `Every account starts with ${PLANS.free.signupCredits} free credits — enough to generate your first store and still have room to refine it. Generating a store costs ${CREDIT_COSTS.storeGeneration} credits; refining it with the AI assistant costs ${CREDIT_COSTS.askMessage} credits a message. Paid plans include a recurring monthly credit allowance, and your credit history is always visible in Billing.`,
  ],
  /*
   * This answer used to say "Yes", and it was true: the free tier ran one live
   * store, because a generated store was born live off the column default. The
   * rule changed — going live is a paid capability now — and this text changes
   * in the same commit as lib/plans.ts on purpose. An FAQ promising free
   * publishing beside a product that refuses it is the drift this whole file is
   * built to prevent, and it is worse than either position taken honestly.
   */
  [
    "Can I publish for free?",
    `No — publishing is where a paid plan starts. Free generates a complete store and lets you refine it as long as you like; taking it live on a urivo.ai address needs ${PLANS.core.name} or ${PLANS.pro.name}. ${PLANS.core.name} runs up to ${PLANS.core.maxLiveStores} live stores and ${PLANS.pro.name} runs as many as you like.`,
  ],
  [
    "Do I need my own domain?",
    "No. Every published store gets a free urivo.ai address the moment you go live. On Founder and Pro you can connect your own domain instead, and your store keeps working at both addresses.",
  ],
  /*
   * Only asked while the offer is open.
   *
   * The cards already fall back to standard pricing once the cap is claimed, but
   * an FAQ answer quoting €29 in the present tense would still be telling a
   * visitor they can get a price the checkout will refuse them. A closed offer
   * is not a question anyone needs answered — so it stops being asked.
   *
   * The wording describes the mechanic as migration 0023 implements it: the spot
   * is claimed when the ACCOUNT is created, not when a payment is made. The
   * previous copy said "subscribe during the launch window", which was both
   * inaccurate and a worse offer than the code actually gives.
   */
  ...(foundingOpen
    ? ([
        [
          "What is the Founding 50?",
          `The first 50 people to create a Urivo account get launch pricing — ${PLANS.core.name} at ${formatPrice(PLANS.core.price.founding ?? PLANS.core.price.regular)} instead of ${formatPrice(PLANS.core.price.regular)}, ${PLANS.pro.name} at ${formatPrice(PLANS.pro.price.founding ?? PLANS.pro.price.regular)} instead of ${formatPrice(PLANS.pro.price.regular)}. The spot is reserved the moment you sign up, not when you pay, and the price stays fixed for the lifetime of your subscription even as standard prices rise. After 50 accounts, new signups pay standard pricing.`,
        ],
      ] as [string, string][])
    : []),
  [
    "Can I cancel anytime?",
    "Anytime, in one click from Billing. You keep access until the end of your current billing period, and you can resubscribe whenever you like.",
  ],
];

/*
 * The storefront the hero promises, on the one screen whose entire job is to
 * show what Urivo produces.
 *
 * This block was a wireframe: flat grey squares where the photography goes and
 * grey pills where the product names go. On a page selling "AI builds you a
 * premium store", the proof-of-product read as unfinished — the single worst
 * thing a generated storefront could look like.
 *
 * The imagery is COMPOSED IN CSS rather than shipped as files, for three
 * reasons and not for cheapness. The page stays self-contained, so there is no
 * asset pipeline and nothing to go stale. A photograph of a real vase would be
 * a picture of someone else's product used to sell ours. And a stock image is
 * exactly the shortcut this product exists to make unnecessary.
 *
 * Each shot is a drawn object on seamless paper, lit from the upper left, with
 * a contact shadow beneath it — which is what a studio product photograph is.
 */
type DemoShape = "vessel" | "throw" | "taper";

const SHAPE: Record<DemoShape, { width: string; height: string; borderRadius: string }> = {
  // An organic thrown vessel: wide shoulder, drawn-in foot.
  vessel: { width: "40%", height: "60%", borderRadius: "44% 44% 34% 34% / 26% 26% 66% 66%" },
  // A folded stack of cloth: soft corners, wider than tall.
  throw: { width: "66%", height: "38%", borderRadius: "10px" },
  // A slim brass taper holder.
  taper: { width: "11%", height: "56%", borderRadius: "3px" },
};

const DEMO_PRODUCTS: { name: string; price: string; shape: DemoShape; body: string }[] = [
  { name: "Fjord stoneware vase", price: "€128", shape: "vessel", body: "linear-gradient(148deg,#DFBC97,#BE8F62 42%,#8C6742)" },
  { name: "Lambswool throw, ash", price: "€154", shape: "throw", body: "linear-gradient(148deg,#DED7CB,#BCB2A2 42%,#918676)" },
  { name: "Brass taper holder", price: "€42", shape: "taper", body: "linear-gradient(148deg,#E6C888,#BE9A4E 42%,#8A6C2E)" },
];

function DemoShot({ shape, body, tall = false }: { shape: DemoShape; body: string; tall?: boolean }) {
  return (
    <div
      className="relative overflow-hidden rounded-lg"
      style={{
        aspectRatio: tall ? "4 / 3" : "1 / 1",
        background: "radial-gradient(125% 95% at 50% 0%, #FCFAF5, #E7E0D3)",
      }}
    >
      {/* Contact shadow. Without it the object floats and the whole thing reads as clipart. */}
      <div
        className="absolute"
        style={{
          left: "50%",
          bottom: "13%",
          width: "56%",
          height: "8%",
          transform: "translateX(-50%)",
          background: "radial-gradient(50% 50% at 50% 50%, rgba(56,42,26,0.36), transparent 72%)",
          filter: "blur(3px)",
        }}
      />
      <div
        className="absolute"
        style={{
          left: "50%",
          bottom: "16%",
          transform: "translateX(-50%)",
          background: body,
          boxShadow: "inset 0 7px 15px rgba(255,255,255,0.40), inset -9px -11px 20px rgba(0,0,0,0.24)",
          ...SHAPE[shape],
        }}
      />
      {/* Folds, so the throw reads as cloth rather than as a rounded rectangle. */}
      {shape === "throw" && (
        <div
          className="absolute"
          style={{
            left: "17%",
            bottom: "16%",
            width: "66%",
            height: "38%",
            borderRadius: "10px",
            background: "repeating-linear-gradient(101deg, rgba(255,255,255,0.15) 0 2px, transparent 2px 16px)",
          }}
        />
      )}
      {/* The holder needs a foot or it reads as a stick. */}
      {shape === "taper" && (
        <div
          className="absolute"
          style={{
            left: "50%",
            bottom: "15%",
            width: "30%",
            height: "4.5%",
            transform: "translateX(-50%)",
            borderRadius: "999px",
            background: body,
            boxShadow: "inset 0 2px 5px rgba(255,255,255,0.42)",
          }}
        />
      )}
    </div>
  );
}

export default async function Home() {
  /*
   * Read from the live counter, not from a date. The offer is capped at 50
   * signups, so it can run out before the launch window closes — and the moment
   * it does, a new visitor pays the standard price. Showing €29 after that
   * would advertise a price the checkout will not honour.
   */
  const founding = await getFoundingOffer();

  return (
    <div className="relative min-h-screen overflow-hidden bg-night text-ivory">
      {/* ambient */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(60% 40% at 50% -5%, rgba(232,205,128,0.10), rgba(11,18,32,0) 55%), radial-gradient(70% 50% at 50% 8%, rgba(36,50,76,0.5), rgba(11,18,32,0) 60%)",
        }}
      />

      {/* Nav */}
      <header className="u-glass sticky top-0 z-40 border-b border-hair">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2.5">
            <Image src={logo} alt="Urivo" width={30} height={30} className="rounded-lg" />
            <span className="text-lg font-semibold tracking-tight text-ivory">Urivo</span>
          </div>
          <div className="flex items-center gap-6 text-sm font-medium">
            <Link href="#pricing" className="hidden text-mist transition-colors hover:text-ivory sm:block">
              Pricing
            </Link>
            <Link href="#faq" className="hidden text-mist transition-colors hover:text-ivory sm:block">
              FAQ
            </Link>
            <Link href="/login" className="u-lift rounded-lg border border-hair bg-panel px-4 py-2 text-sm font-medium text-ivory hover:border-hair-strong hover:bg-panel-2">
              Sign in
            </Link>
            <Link href="/login" className="u-gold u-lift rounded-lg px-4 py-2 text-sm font-semibold">
              Get started
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative mx-auto max-w-4xl px-6 pt-24 text-center sm:pt-28">
        <div className="u-glass mx-auto mb-8 inline-flex items-center gap-2 rounded-full border border-hair px-4 py-1.5 text-xs font-semibold text-gold-soft">
          <span className="h-1.5 w-1.5 rounded-full bg-gold" style={{ boxShadow: "0 0 8px rgba(232,205,128,0.7)" }} />
          The AI Commerce Operating System
        </div>
        <h1 className="text-5xl font-semibold leading-[1.05] tracking-tight text-ivory sm:text-7xl">
          Describe your business.
          <br />
          <span className="u-gold-text">Urivo builds it.</span>
        </h1>
        <p className="mx-auto mt-8 max-w-xl text-lg leading-relaxed text-mist">
          Market research, brand identity, product catalog and a live storefront —
          generated by AI in under a minute, refined by you.
        </p>
        <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
          <Link href="/login" className="u-gold u-lift w-full rounded-xl px-8 py-3.5 text-sm font-semibold sm:w-auto">
            Start your store →
          </Link>
          <Link href="#pricing" className="u-lift w-full rounded-xl border border-hair bg-panel px-8 py-3.5 text-sm font-semibold text-ivory hover:border-hair-strong hover:bg-panel-2 sm:w-auto">
            See pricing
          </Link>
        </div>
        <p className="mt-5 text-xs text-mist-dim">No credit card required</p>
      </section>

      {/* Product visual — see DemoShot above for why the imagery is drawn. */}
      <section className="relative mx-auto mt-10 max-w-5xl px-6 sm:mt-12">
        <div className="u-float overflow-hidden rounded-2xl border border-hair bg-panel/70">
          <div className="flex items-center gap-1.5 border-b border-hair px-4 py-2.5">
            <span className="h-2.5 w-2.5 rounded-full bg-alert/70" />
            <span className="h-2.5 w-2.5 rounded-full bg-gold/70" />
            <span className="h-2.5 w-2.5 rounded-full bg-live/70" />
            <span className="mx-auto rounded-md bg-night px-3 py-1 font-mono text-[11px] text-mist-dim">nordljus.urivo.ai</span>
          </div>

          <div style={{ background: "#F4F0E8", color: "#23272C" }}>
            {/*
              The merchant's own navigation, in the merchant's own colours. An
              ink bar under the browser chrome is what stops the whole block
              reading as a blank page with boxes on it.
            */}
            <div className="flex items-center justify-between px-5 py-3 sm:px-7" style={{ background: "#1C2025", color: "#F2EFE9" }}>
              <span className="text-[12px] font-semibold tracking-[0.3em] sm:text-[13px]" style={{ fontFamily: "Georgia, serif" }}>
                NORDLJUS
              </span>
              <div className="hidden items-center gap-7 text-[11px] tracking-wide sm:flex" style={{ opacity: 0.66 }}>
                <span>Objects</span>
                <span>Textiles</span>
                <span>Lighting</span>
              </div>
              <span className="text-[11px]" style={{ opacity: 0.66 }}>Cart (0)</span>
            </div>

            <div className="grid items-center gap-7 px-5 py-7 sm:grid-cols-[1fr_1fr] sm:gap-10 sm:px-8 sm:py-9">
              <div>
                <p className="text-[10px] font-semibold uppercase tracking-[0.24em]" style={{ color: "#A98551" }}>
                  Autumn collection
                </p>
                <h3
                  className="mt-3 text-[30px] leading-[1.06] tracking-tight sm:text-[38px]"
                  style={{ fontFamily: "Georgia, serif", fontWeight: 500 }}
                >
                  Quiet luxury for
                  <br />
                  the Scandinavian home.
                </h3>
                <p className="mt-4 max-w-[34ch] text-[13px] leading-relaxed" style={{ opacity: 0.66 }}>
                  Stoneware thrown in Jutland, lambswool woven in Borås. Made in
                  small numbers, kept for decades.
                </p>
                <span
                  className="mt-6 inline-block rounded-md px-5 py-2.5 text-[12px] font-semibold tracking-wide"
                  style={{ background: "#1C2025", color: "#F2EFE9" }}
                >
                  Shop the collection
                </span>
              </div>
              <div className="hidden sm:block">
                <DemoShot shape="vessel" body="linear-gradient(148deg,#E0BE99,#C09164 42%,#8F6A44)" tall />
              </div>
            </div>

            <div className="grid grid-cols-3 gap-3 px-5 pb-7 sm:gap-5 sm:px-8 sm:pb-9">
              {DEMO_PRODUCTS.map((p) => (
                <div key={p.name}>
                  <DemoShot shape={p.shape} body={p.body} />
                  <p className="mt-2.5 text-[11px] font-medium leading-snug sm:text-[12.5px]">{p.name}</p>
                  <p className="mt-0.5 text-[11px] font-semibold sm:text-[12px]" style={{ color: "#A98551" }}>
                    {p.price}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/*
        * How it works. The hero above is deliberately left alone — it is the
        * first paint and must simply be there. From here down the page assembles
        * as you scroll: RevealStagger takes the grid's own classes, so the cards
        * stay the grid's direct children and the layout is byte-for-byte what it
        * was without it.
        */}
      <section className="mx-auto max-w-5xl px-6 py-24">
        <RevealStagger className="grid gap-4 sm:grid-cols-3">
          {[
            ["Describe", "Tell Urivo what you want to sell — one sentence is enough."],
            ["Generate", "AI designs your brand, writes your catalog and builds the store."],
            ["Sell", "Your storefront gets its own address, ready to refine and publish."],
          ].map(([title, body], i) => (
            <div key={title} className="u-float rounded-2xl border border-hair bg-panel/70 p-7">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg border border-gold/20 bg-gold/[0.06] text-sm font-semibold text-gold">
                {i + 1}
              </div>
              <h3 className="mt-5 text-lg font-semibold text-ivory">{title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-mist">{body}</p>
            </div>
          ))}
        </RevealStagger>
      </section>

      {/* Pricing */}
      <section id="pricing" className="mx-auto max-w-6xl px-6 pb-24">
        <Reveal className="text-center">
          {founding.open && (
            <span className="mb-5 inline-flex items-center gap-2.5 rounded-full border border-gold/25 bg-gold/[0.06] px-4 py-1.5 text-[11px] font-semibold uppercase tracking-[0.18em] text-gold-soft">
              <span className="h-1 w-1 rounded-full bg-gold" aria-hidden="true" />
              Founding 50
            </span>
          )}
          <h2 className="text-4xl font-semibold tracking-tight text-ivory">Simple, premium pricing</h2>
          <p className="mt-3 text-mist">
            {founding.open
              ? "Launch pricing for the first 50 Urivo merchants, locked for life."
              : "From your idea to a live store in minutes."}
          </p>
        </Reveal>

        <RevealStagger className="mt-14 grid gap-6 md:grid-cols-3">
          {TIERS.map((tier) => (
            <div
              key={tier.name}
              className={`u-float flex flex-col rounded-2xl border bg-panel/70 p-8 ${
                tier.highlight ? "border-gold/40 ring-1 ring-gold/15" : "border-hair"
              }`}
            >
              {tier.highlight && (
                <span className="u-gold mb-4 self-start rounded-full px-3 py-1 text-xs font-semibold">Most popular</span>
              )}
              <h3 className="text-xl font-semibold text-ivory">{tier.name}</h3>
              {/*
                * The founding price is the dominant number and the standard one
                * is struck through beside it, so it reads as a launch price
                * rather than as the permanent price. Once the 50 are claimed the
                * card falls back to the standard price alone — the same
                * component, telling the truth in both states.
                */}
              <div className="mt-5 flex items-baseline gap-2.5">
                <span className="text-5xl font-semibold tracking-tight text-ivory">
                  {founding.open && tier.founding ? tier.founding : tier.standard}
                </span>
                {founding.open && tier.founding && (
                  <span className="text-lg text-mist/70 line-through decoration-mist/50">
                    {tier.standard}
                  </span>
                )}
              </div>
              <p className="mt-1 text-sm text-mist">{tier.cadence}</p>

              <ul className="mt-8 flex-1 space-y-3 text-sm text-ivory/85">
                {tier.features.map((f) => (
                  <li key={f} className="flex items-start gap-2.5">
                    <svg className="mt-0.5 h-4 w-4 shrink-0 text-gold" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.7 5.3a1 1 0 0 1 0 1.4l-7.5 7.5a1 1 0 0 1-1.4 0L3.3 9.7a1 1 0 1 1 1.4-1.4l3.3 3.3 6.8-6.8a1 1 0 0 1 1.4 0Z" clipRule="evenodd" />
                    </svg>
                    {f}
                  </li>
                ))}
              </ul>

              <Link
                href="/login"
                className={`u-lift mt-8 rounded-xl px-6 py-3 text-center text-sm font-semibold ${
                  tier.highlight ? "u-gold" : "border border-hair bg-panel text-ivory hover:border-hair-strong hover:bg-panel-2"
                }`}
              >
                {tier.cta}
              </Link>
            </div>
          ))}
        </RevealStagger>
        <p className="mt-8 text-center text-sm text-mist">
          {founding.open
            ? "Limited to the first 50 Urivo merchants. Your founding price stays fixed for the lifetime of your subscription. Prices in EUR, cancel anytime."
            : "Prices in EUR. Cancel anytime."}
        </p>
      </section>

      {/* FAQ */}
      <section id="faq" className="mx-auto max-w-3xl px-6 pb-24">
        <Reveal as="h2" className="text-center text-3xl font-semibold tracking-tight text-ivory">
          Questions, answered
        </Reveal>
        {/* One reveal for the whole panel — staggering rows inside a divided
            list reads as the list redrawing itself, not as it arriving. */}
        <Reveal className="u-float mt-10 divide-y divide-hair overflow-hidden rounded-2xl border border-hair bg-panel/70">
          {FAQ(founding.open).map(([q, a]) => (
            <details key={q} className="group px-6 py-5 [&_summary::-webkit-details-marker]:hidden">
              <summary className="flex cursor-pointer items-center justify-between gap-4 text-base font-medium text-ivory">
                {q}
                <svg className="h-5 w-5 shrink-0 text-gold transition-transform duration-200 group-open:rotate-45" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round">
                  <path d="M10 4v12M4 10h12" />
                </svg>
              </summary>
              <p className="mt-3 text-sm leading-relaxed text-mist">{a}</p>
            </details>
          ))}
        </Reveal>
      </section>

      {/* Footer */}
      <footer className="border-t border-hair">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 px-6 py-10 sm:flex-row">
          <div className="flex items-center gap-2.5">
            <Image src={logo} alt="Urivo" width={22} height={22} className="rounded-md" />
            <p className="text-sm text-mist">© {new Date().getFullYear()} Urivo</p>
          </div>
          {/* -my-2 py-2: a finger-sized target on a phone, with the row's
              visual position unchanged. */}
          <div className="flex gap-6 text-sm font-medium text-mist">
            <Link href="/impressum" className="-my-2 py-2 transition-colors hover:text-ivory">Legal Notice</Link>
            <Link href="/datenschutz" className="-my-2 py-2 transition-colors hover:text-ivory">Privacy Policy</Link>
            <Link href="/agb" className="-my-2 py-2 transition-colors hover:text-ivory">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
